config:
  backup: true
  banner: true
  create: true
  dotpath: ~/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  d_icons:
    src: icons
    dst: ~/.icons
  f_xauthority:
    src: Xauthority
    dst: ~/.Xauthority
    chmod: '600'
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_lf:
    src: config/lf
    dst: ~/.config/lf
  d_ncmpcpp:
    src: config/ncmpcpp
    dst: ~/.config/ncmpcpp
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_dwm:
    src: local/share/dwm
    dst: ~/.local/share/dwm
  f_make.conf:
    src: etc/portage/make.conf
    dst: /etc/portage/make.conf
  f_merguse:
    src: etc/portage/package.use/merguse
    dst: /etc/portage/package.use/merguse
  d_merg:
    src: var/db/repos/merg
    dst: /var/db/repos/merg
  d_pragmatapro:
    src: usr/share/fonts/PragmataPro
    dst: /usr/share/fonts/PragmataPro
  f_mpd.conf:
    src: etc/mpd.conf
    dst: /etc/mpd.conf
profiles:
  gentoo:
    dotfiles:
    - f_xinitrc
    - f_bashrc
    - f_bash_profile
    - d_icons
    - f_xauthority
    - f_xresources
    - d_fish
    - d_gtk-3.0
    - d_lf
    - d_ncmpcpp
    - d_picom
    - d_dwm
    - f_make.conf
    - f_merguse
    - d_merg
    - d_pragmatapro
    - f_mpd.conf
