config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: home/mergen/.zshrc
    dst: /home/mergen/.zshrc
  f_config:
    src: home/mergen/.config/sway/config
    dst: /home/mergen/.config/sway/config
  d_alacritty:
    src: home/mergen/.config/alacritty
    dst: /home/mergen/.config/alacritty
  d_mpd:
    src: home/mergen/.config/mpd
    dst: /home/mergen/.config/mpd
  d_ranger:
    src: home/mergen/.config/ranger
    dst: /home/mergen/.config/ranger
  d_wofi:
    src: home/mergen/.config/wofi
    dst: /home/mergen/.config/wofi
  f_ncmpcpp_config:
    src: home/mergen/.config/ncmpcpp/config
    dst: /home/mergen/.config/ncmpcpp/config
  f_default.pa:
    src: home/mergen/.config/pulse/default.pa
    dst: /home/mergen/.config/pulse/default.pa
  d_waybar:
    src: home/mergen/.config/waybar
    dst: /home/mergen/.config/waybar
  d_pragmatapro:
    src: usr/share/fonts/PragmataPro
    dst: /usr/share/fonts/PragmataPro
  d_pictures:
    src: home/mergen/Pictures
    dst: /home/mergen/Pictures
  d_kitty:
    src: home/mergen/.config/kitty
    dst: /home/mergen/.config/kitty
  d_nvim:
    src: home/mergen/.config/nvim
    dst: /home/mergen/.config/nvim
profiles:
  archlinux:
    dotfiles:
    - f_zshrc
    - f_config
    - d_alacritty
    - d_mpd
    - d_ranger
    - d_wofi
    - f_ncmpcpp_config
    - f_default.pa
    - d_waybar
    - d_pragmatapro
    - d_pictures
    - d_kitty
    - d_nvim
